webdriver_basic:
  image: selenium/standalone-firefox
  links:
    - example_basic
  ports:
    - "4444:4444"

webdriver_full:
  image: selenium/standalone-firefox
  links:
    - example_full
  ports:
    - "4444:4444"

example_basic:
  build: .
  dockerfile: example_basic.dockerfile
  ports:
   - "8000:8000"
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_example_basic.sh

example_full:
  build: .
  dockerfile: example_full.dockerfile
  ports:
    - "3000:3000"
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_example_full.sh

test_unit:
  build: .
  dockerfile: test_unit.dockerfile
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_test_unit.sh

test_example_basic:
  build: ./test/integration/examples/both
  links:
    - example_basic
    - webdriver_basic
  volumes:
    - ./test/integration/examples/both:/usr/src
  working_dir: /usr/src
  command: ./run.sh
  environment:
    APP_HOST: example_basic
    APP_PORT: 8000
    WEBDRIVER_HOST: webdriver_basic
    WEBDRIVER_PORT: 4444
    TEST_DIR: basic

test_example_full:
  build: ./test/integration/examples/both
  links:
    - example_full
    - webdriver_full
  volumes:
    - ./test/integration/examples/both:/usr/src
  working_dir: /usr/src
  command: ./run.sh
  environment:
    APP_HOST: example_full
    APP_PORT: 8000
    WEBDRIVER_HOST: webdriver_full
    WEBDRIVER_PORT: 4444
    TEST_DIR: full
