webdriver:
  image: selenium/standalone-firefox
  links:
    - example_basic:app
  ports:
    - "4444:4444"

example_basic:
  build: .
  dockerfile: example_basic.dockerfile
  ports:
   - "8000:8000"
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_example_basic.sh

example_full:
  build: .
  dockerfile: example_full.dockerfile

test_unit:
  build: .
  dockerfile: test_unit.dockerfile
  volumes:
    - .:/usr/src
  working_dir: /usr/src
  command: ./start_test_unit.sh

test_example_basic:
  build: ./test/integration/examples/basic
  links:
    - webdriver
    - example_basic:app
  volumes:
    - ./test/integration/examples/basic:/usr/src
  working_dir: /usr/src
  command: ./start.sh
